password="" # sower password

[client]
  address = "" # aa.bb.cc, socks5h://127.0.0.1:1080
  http_proxy=":8080"
  dns_serve_ip="" # eg: 127.0.0.1. keep empty to disable DNS solution
  dns_upstream="" # keep empty to set via dhcp, not effective in any environment

  [client.port_forward]
    # eg: ":2222"="aa.bb.cc:22"

  [client.router]
    detect_level = 2 # 0~4, the bigger the harder to add
    detect_timeout = "500ms"
    direct_list = [
      "**.in-addr.arpa",
      "imap.*.*",
      "imap.*.*.*",
      "smtp.*.*",
      "smtp.*.*.*",
      "pop.*.*",
      "pop.*.*.*",
      "**.cn",
    ]
    proxy_list = [
      "**.google.*",
      "**.goo.gl",
      "**.googleusercontent.com",
      "**.googleapis.com",
      "*.googlesource.com",
      "**.youtube.com",
      "**.ytimg.com",
      "**.ggpht.com",
      "**.googlevideo.com",
      "**.facebook.com",
      "**.fbcdn.net",
      "**.twitter.com",
      "**.twimg.com",
      "**.blogspot.com",
      "**.appspot.com",
      "**.wikipedia.org",
      "*.cloudfront.net",
      "**.amazon.com",
      "**.amazonaws.com",
      "*.githubusercontent.com",
      "*.githubassets.com",
      "*.github.*",
    ]


[server]
  cert_email = "" # eg: user@aa.bb.cc
  cert_file = "" # eg: /etc/ssl/server.crt
  key_file = "" # eg: /etc/ssl/server.key
  upstream = "" # eg: 127.0.0.1:8080